apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "casbin-forward-auth.fullname" . }}-config
  labels:
    {{- include "casbin-forward-auth.labels" . | nindent 4 }}
data:
  auth-route-config.yaml: |
    {{ toYaml .Values.application.authRouteConfig | nindent 4 }}
