{{- if .Values.application.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "casbin-forward-auth.fullname" . }}-env
  labels:
    {{- include "casbin-forward-auth.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.application.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}