---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "casbin-forward-auth.fullname" . }}
  labels:
    {{- include "casbin-forward-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "casbin-forward-auth.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "casbin-forward-auth.fullname" . }}-admin
  labels:
    {{- include "casbin-forward-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "casbin-forward-auth.selectorLabels" . | nindent 4 }}
